### ISSUE TITLE
Include lodash as module dependence

### ISSUE THREAD

**Issue by muZk** [archangel-irk/storage#6]
Files in general don't have lodash dependence, for example, in https://github.com/archangel-irk/storage/blob/master/lib/schema.js, it should be:

``` javascript
/*!
 * Module dependencies.
 */

var Events = require('./events')
  , VirtualType = require('./virtualtype')
  , utils = require('./utils')
  , Types
  , schemas
  , _ = require('lodash')
```

**Comment by archangel-irk** [comment]
Yes, you are right, thank you very much. Tonight will be fixed.

**Comment by archangel-irk** [comment]
Now assumes that you have already loaded lodash on the page, I'll try to change it in the build.

**Comment by archangel-irk** [comment]
You think it's a good idea to put lodash in the build? I think it's better to leave as is, or use externals http://webpack.github.io/docs/library-and-externals.html

**Comment by muZk** [comment]
I encoured "_ is not definined" when I tried to use each module standalone. 

I know that the library is build to be used with *storage.min.js* file, which works perfectly. But I tried to make a file like https://github.com/Automattic/mongoose/blob/master/lib/index.js , in order to have the exact mongoose synthax to support Isomorphic javascript http://nerds.airbnb.com/isomorphic-javascript-future-web-apps/

**Comment by archangel-irk** [comment]
On the server you still have to use mongoose. Storage is a client-only library. Isomorphic does not work, at least because the schema for the client and server should be different for security reasons as well as Storage uses a different (more convenient) api for inheritance schemes.
```js
var PersonSchema = new Schema('Person', {
  name: String,
  createdAt: Date
});

var BossSchema = new Schema('Boss', PersonSchema, { department: String });
```
But in everything else (such as page rendering, routing ... ) you can use an isomorphic approach. That's the way it works in my projects. I am using https://github.com/archangel-irk/rest-api-client to get data from the server and immediately wrapped in Document in Storage. 

In the mongoose now also has support for client side https://github.com/Automattic/mongoose/tree/master/bin. Though there is a lot of unused code and fewer opportunities for the client compared to the Storage.

You can also try meteor (https://www.meteor.com/)

Storage is a library to support such schemes as in mongoose on the client, but the schema files you will still be different for the server and the client.

**Comment by muZk** [comment]
Oks! thanks for clarifying it out. 

You're right, there are security reasons. Maybe there is a way to support sharing a subset of fields/methods of models (to avoid code duplication and security risks).

I was making a isomorphic app from scratch with the aim of learn more about it and its limitations. In the search of a library for sharing models I found storage, which seems pretty good :+1:

Now I'm more agnostic about the idea of sharing models but still trying to figure out how to avoid code duplication while sharing components.

For real proyects I would use meteor as you mentioned in your comments!

Back on topic, I think you're right, keep it as is it!

**Comment by archangel-irk** [comment]
In the case of mongoose and storage it is better to use different schemes for the client and the server. Anyway some fields are not needed on the client. But if you really want, you can use the technique of mixing to separate the base model and add to it the server-specific fields.

Speaking of meteor yet we should remember about http://derbyjs.com/

**Comment by archangel-irk** [comment]
If you have any questions on the use of storage, I'll be happy to help you.
